[INFO]	2023-04-27T22:03:57.595Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T22:03:57.596Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T22:03:57.600Z	logger.py	write_lambda_event	92	[event.json] {"queryStringParameters": {"id": "9d799344-49eb-4379-8305-24102c7b1d4d"}}
[INFO]	2023-04-27T22:03:57.608Z	credentials.py	load	1255	Found credentials in shared credentials file: ~/.aws/credentials
[INFO]	2023-04-27T22:03:58.562Z	logger.py	write_lambda_result	102	[result] {"statusCode": 200, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{\"author\": \"F. Scott Fitzgerald\", \"cover_image_url\": \"https://example.com/cover/great_gatsby.jpg\", \"created_at\": \"\\\"2023-04-21T10:24:30.985669+0000\\\"\", \"id\": \"9d799344-49eb-4379-8305-24102c7b1d4d\", \"isbn\": \"9780743273565\", \"jst_created_at\": \"2023-04-21T19:24:30.985669+0900\", \"jst_updated_at\": \"2023-04-21T19:24:30.985669+0900\", \"published_date\": \"1925-04-10\", \"publisher\": \"Scribner\", \"title\": \"The Great Gatsby\", \"updated_at\": \"\\\"2023-04-21T10:24:30.985669+0000\\\"\", \"updated_user\": \"test_user\"}"}
[INFO]	2023-04-27T22:09:10.11Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T22:09:10.11Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T22:09:10.15Z	logger.py	write_lambda_event	88	[event.json] {"queryStringParameters": {"id": "9d799344-49eb-4379-8305-24102c7b1d4d"}}
[INFO]	2023-04-27T22:09:10.23Z	credentials.py	load	1255	Found credentials in shared credentials file: ~/.aws/credentials
[INFO]	2023-04-27T22:09:10.969Z	logger.py	write_lambda_result	98	[result] {"statusCode": 200, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{\"author\": \"F. Scott Fitzgerald\", \"cover_image_url\": \"https://example.com/cover/great_gatsby.jpg\", \"created_at\": \"\\\"2023-04-21T10:24:30.985669+0000\\\"\", \"id\": \"9d799344-49eb-4379-8305-24102c7b1d4d\", \"isbn\": \"9780743273565\", \"jst_created_at\": \"2023-04-21T19:24:30.985669+0900\", \"jst_updated_at\": \"2023-04-21T19:24:30.985669+0900\", \"published_date\": \"1925-04-10\", \"publisher\": \"Scribner\", \"title\": \"The Great Gatsby\", \"updated_at\": \"\\\"2023-04-21T10:24:30.985669+0000\\\"\", \"updated_user\": \"test_user\"}"}
[INFO]	2023-04-27T23:02:26.736Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:02:26.736Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:02:26.740Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:02:26.741Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 19, in process
    check_parameters(body)
  File "post_book.py", line 30, in check_parameters
    raise NgTitleError([f"[{title}]"])
TypeError: __new__() takes 1 positional argument but 2 were given

[INFO]	2023-04-27T23:02:26.741Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:02:52.276Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:02:52.276Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:02:52.281Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:03:04.185Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
TypeError: __new__() takes 1 positional argument but 2 were given

[INFO]	2023-04-27T23:03:04.186Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:04:06.299Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:04:06.299Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:04:06.304Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:04:16.386Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 14, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 64, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:04:26.62Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:05:19.193Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:05:19.193Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:05:19.198Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:05:26.213Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 14, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 66, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:05:26.214Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:05:50.375Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:05:50.375Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:05:50.379Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:05:53.688Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "/home/user/project1-back/src/common/error/application_error.py", line 13, in __new__
    return super().__new__(*args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 39, in __new__
    return super().__new__(cls, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type

[INFO]	2023-04-27T23:05:53.688Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:08:00.621Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:08:00.621Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:08:00.626Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:08:07.301Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 17, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 66, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:08:07.303Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:09:00.138Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:09:00.139Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:09:00.143Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:09:08.905Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 20, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 66, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:09:08.905Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:10:31.249Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:10:31.250Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:10:31.254Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:10:54.392Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 26, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 70, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:10:54.393Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:11:42.467Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:11:42.467Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:11:42.471Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:11:57.667Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 26, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 70, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:11:57.668Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:11:59.672Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:11:59.672Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:11:59.677Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:12:16.76Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 26, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 70, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:12:16.77Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:12:53.799Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:12:53.799Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:12:53.804Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:13:06.290Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 71, in __init__
    super().__init__("NgTitleError", *args)
  File "/home/user/project1-back/src/common/error/application_error.py", line 26, in __init__
    self.__message = super().get_message(label, args)
  File "/home/user/project1-back/src/common/error/base_error.py", line 70, in get_message
    message: str = self.error_message_dict[label]["message"]
AttributeError: 'NgTitleError' object has no attribute 'error_message_dict'

[INFO]	2023-04-27T23:13:06.291Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:13:51.171Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:13:51.171Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:13:51.175Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:14:14.752Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return super(Singleton, cls).__new__(cls, *args, **kwargs)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:14:14.752Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:19:36.765Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:19:36.765Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:19:36.769Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:20:05.552Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return super(Singleton, cls).__new__(cls, *args, **kwargs)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:20:05.553Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:22:19.878Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:22:19.879Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:22:19.883Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:22:30.992Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return super(Singleton, cls).__new__(cls)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:22:30.992Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:24:41.935Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:24:41.935Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:24:41.939Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:24:47.653Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return Singleton.__new__(cls)
  File "/home/user/project1-back/src/common/python/singleton.py", line 13, in __new__
    cls._instance = super(Singleton, cls).__new__(cls)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:24:47.653Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:24:53.104Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:24:53.104Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:24:53.110Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:24:55.767Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return Singleton.__new__(cls)
  File "/home/user/project1-back/src/common/python/singleton.py", line 13, in __new__
    cls._instance = super(Singleton, cls).__new__(cls)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:24:55.768Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:25:16.733Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:25:16.733Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:25:16.737Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:25:39.704Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return Singleton.__new__(cls)
  File "/home/user/project1-back/src/common/python/singleton.py", line 13, in __new__
    cls._instance = super(Singleton, cls).__new__(cls)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:25:39.705Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:26:47.99Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:26:47.99Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:26:47.104Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:26:54.316Z	logger.py	write_error	75	Traceback (most recent call last):
  File "/home/user/project1-back/src/common/aws/lambda_handler.py", line 87, in api_handler
    return function(event, context)
  File "post_book.py", line 28, in process
    check_parameters(body)
  File "post_book.py", line 39, in check_parameters
    raise NgTitleError([f"[{title}]"])
  File "post_book.py", line 68, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/application_error.py", line 15, in __new__
    return super().__new__(cls, *args, **kwargs)
  File "/home/user/project1-back/src/common/error/base_error.py", line 41, in __new__
    return Singleton.__new__(cls)
  File "/home/user/project1-back/src/common/python/singleton.py", line 13, in __new__
    cls._instance = super().__new__(cls)
TypeError: object.__new__(NgTitleError) is not safe, use Exception.__new__()

[INFO]	2023-04-27T23:26:54.317Z	logger.py	write_lambda_result	98	[result] {"statusCode": 500, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{}"}
[INFO]	2023-04-27T23:27:10.312Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:27:10.312Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:27:10.316Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[INFO]	2023-04-27T23:28:11.310Z	settings.py	<module>	39	Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[INFO]	2023-04-27T23:28:11.311Z	settings.py	<module>	40	Using Default settings value
[INFO]	2023-04-27T23:28:11.315Z	logger.py	write_lambda_event	88	[event.json] {"body": {"title": "Error 1", "author": "author1", "publisher": "publisher1", "publishedDate": "2023-04-21", "isbn": "9999999999999", "coverImageUrl": "https://example.com/cover/book1.jpg"}}
[ERROR]	2023-04-27T23:28:25.43Z	logger.py	write_error	75	{"message": "登録できないタイトルが設定されています。[Error 1]"}
[INFO]	2023-04-27T23:28:25.43Z	logger.py	write_lambda_result	98	[result] {"statusCode": 290, "headers": {"Access-Control-Allow-Origin": "*", "Cache-Control": "max-age=0", "X-FRAME-OPTIONS": "DENY", "X-Content-Security-Policy": "default-src 'self'"}, "body": "{\"message\": \"登録できないタイトルが設定されています。[Error 1]\"}"}
